### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by mikob** [ejoubaud/cypress-browser-extension-plugin#6]
Steps:
`$ yarn add --dev cypress cypress-browser-extension-plugin`

Edit the plugins/index.js file to this:
```
const extensionLoader = require('cypress-browser-extension-plugin/loader');

/**
 * @type {Cypress.PluginConfig}
 */
module.exports = (on) => {
  on('before:browser:launch', extensionLoader.load('../../package'));
}

// cypress/support/command.js
const addExtensionCommands = require('cypress-browser-extension-plugin/commands');
addExtensionCommands(Cypress);

// cypress/integration/my_spec.js or cypress/support/index.js
beforeEach(() => {
  cy.clearExtensionStorage('local');
});
```

`$ npx cypress open`

Error:
The plugins file is missing or invalid.

Your pluginsFile is set to /home/mikob/workspace/lipsurf/chrome-extension/cypress/plugins/index.js, but either the file is missing, it contains a syntax error, or threw an error when required. The pluginsFile must be a .js or .coffee file.

Or you might have renamed the extension of your pluginsFile to .ts. If that's the case, restart the test runner.

Please fix this, or set pluginsFile to false if a plugins file is not necessary for your project.
```
ReferenceError: window is not defined
    at Object.<anonymous> (<redacted>/node_modules/cypress-browser-extension-plugin/helpers.js:8:22)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

**Comment by mshin1717** [comment]
I did the same thing. Make sure to move the following command to cypress/support/command.js file.

`const addExtensionCommands = require('cypress-browser-extension-plugin/commands');
addExtensionCommands(Cypress);`

Also remove the beforeEach statement or move it into your tests.
